# Generated by Django 3.0.3 on 2020-02-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ccode', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logos')),
                ('banner', models.ImageField(upload_to='banners')),
                ('about', models.TextField()),
                ('address', models.TextField()),
                ('website', models.URLField()),
                ('gmaplink', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('mobile', models.BigIntegerField()),
                ('ad_banner1', models.ImageField(upload_to='adsection1')),
                ('ad_2', models.ImageField(upload_to='adsection2')),
                ('ad_3', models.ImageField(upload_to='adsection3')),
                ('ad_footer1', models.ImageField(upload_to='adsection4')),
                ('ad_gridbottom', models.ImageField(upload_to='adsection5')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccode1', models.CharField(max_length=50)),
                ('coursepythontype', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
            ],
        ),
    ]
