# Generated by Django 3.0.3 on 2020-02-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetails',
            old_name='coursepythontype',
            new_name='coursetype',
        ),
    ]
