# Generated by Django 3.0.3 on 2020-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200227_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_catagory',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
