# Generated by Django 3.0.3 on 2020-03-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_collegecatagories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegecatagories',
            old_name='caragory',
            new_name='catagory',
        ),
    ]
