# Generated by Django 3.0.3 on 2020-03-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200305_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='ad_3',
        ),
    ]
