# Generated by Django 3.0.3 on 2020-03-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_college_ad_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='ad_gridbottom',
        ),
    ]
