# Generated by Django 3.0.3 on 2020-03-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_college_ad_gridbottom'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
